version: "3.8"
services:
  db:
    image: postgres:14.8-alpine
    restart: always
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=restaurant
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
volumes:
  db:
    driver: local
